version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node:lts
    steps:
      - checkout
      - run:
          name: update-yarn
          command: 'curl --compressed -o- -L https://yarnpkg.com/install.sh | bash'
      - run:
          name: install-dependencies
          command: yarn install
      - run:
          name: compile-translations
          command: yarn translate
      - run:
          name: test
          command: yarn test
