version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout
      - run:
          name: update-yarn
          command: 'curl --compressed -o- -L https://yarnpkg.com/install.sh | bash'
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: install-yarn
          command: yarn install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: test
          command: yarn test
      - store_artifacts:
          path: test-results.xml
          prefix: tests
      - store_test_results:
          path: test-results.xml
