version: 2.1
workflows:
  workflow:
    jobs:
      - test:
          name: test

      - deploy:
          name: deploy
          filters:
            branches:
              only:
                - next
          requires:
            - test

jobs:
  test:
    docker:
      - image: cimg/node:lts
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - node_modules-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile
      - save_cache:
          name: Save Yarn Package Cache
          key: node_modules-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
            - ~/.cache
          background: true
      - run:
          name: test
          command: yarn test

  deploy:
    docker:
      - image: cimg/node:lts
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - node_modules-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile
      - save_cache:
          name: Save Yarn Package Cache
          key: node_modules-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
            - ~/.cache
          background: true
      - run:
          name: build
          command: yarn build
      - run:
          name: deploy
          command: yarn deploy
